# -*- coding: utf-8 -*-
"""DISEF_gen_qwen (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2gN-uR0rIrMi31GWHkNzxZV0mb7Mos9

# Synthetic Image Generation with Qwen3-VL Filtering

Pipeline: **few-shot real images → LLaVA captions → Stable Diffusion image-to-image generation → Qwen3-VL zero-shot filtering → save accepted images**.

This notebook replaces the original CLIP filtering stage with Qwen3-VL-Embedding-2B while keeping the LLaVA + Stable Diffusion generation pipeline.
"""

# ============================================================
# 1. CONFIGURATION
# ============================================================
import os
import sys
import pickle
import random
import torch
import torch.nn.functional as F
import torchvision.transforms as tfms
import numpy as np
from PIL import Image


from diffusers import (
    StableDiffusionPipeline,
    DPMSolverMultistepScheduler,
)
SPC_ROOT = "/content/SPC"

# Dataset produced by the original pipeline
DATASETS_ROOT = f"{SPC_ROOT}/datasets-by-seed"

# Output
OUTPUT_ROOT = f"{SPC_ROOT}/sap_generated_images_qwen"

# Experiment
DATASET = "fgvc_aircraft"          # dtd / eurosat / cars / pets / flowers / fgvca
SEED = 2
STARTING_STEP = 10
BATCH_SIZE = 32            # Start with 1 or 2 on T4
CFG_STRENGTH = 8.0
IMAGES_PER_CLASS = 64         # Test first; change to 64 later
MIXUP = False
USE_LLAVA = True

# Models
SD_MODEL_NAME = "stable_diffusion"
SD_MODEL_ID = "sd2-community/stable-diffusion-2-1"
LLAVA_MODEL_PATH = "liuhaotian/llava-v1.5-7b"

# Use the same Qwen model that you tested successfully.
# It can be a Hugging Face repo ID or a local checkpoint directory.
QWEN_MODEL_PATH = "/content/models/Qwen3-VL-Embedding-2B"

if SPC_ROOT not in sys.path:
    sys.path.insert(0, SPC_ROOT)

LLAVA_ROOT = f"{SPC_ROOT}/LLaVA"
if LLAVA_ROOT not in sys.path:
    sys.path.insert(0, LLAVA_ROOT)

random.seed(22)
np.random.seed(22)
torch.manual_seed(22)

print("SPC:", SPC_ROOT)
print("Dataset:", DATASET)
print("CUDA:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

"""## 2. Install dependencies"""

!pip install -q -U diffusers transformers accelerate bitsandbytes sentencepiece huggingface_hub

"""## 3. Import SPC and LLaVA modules"""

!git clone https://github.com/canhdinhtien/SPC.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/SPC

!git clone https://github.com/haotian-liu/LLaVA.git

!git clone https://github.com/QwenLM/Qwen3-VL-Embedding.git

!pip install huggingface-hub
!hf download Qwen/Qwen3-VL-Embedding-2B --local-dir ./models/Qwen3-VL-Embedding-2B
!pip install qwen-vl-utils

!pip install munch

import sys
import os

from data import get_data_loader
from utils import fix_random_seeds, get_dataset_name_for_template
from util_data import SUBSET_NAMES, TEMPLATES_SMALL
import torch
from models.qwen.src.models.qwen3_vl_embedding import Qwen3VLEmbedder
from qwen_utils import get_image_embedding

import sys
sys.path.append("/content/SPC/LLaVA")


import os
import sys

PROJECT_ROOT = "/content/SPC"

os.chdir(PROJECT_ROOT)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("Current directory:", os.getcwd())
print("Project root in sys.path:", PROJECT_ROOT in sys.path)

from llava_processor import LlaVaProcessor
from llava.conversation import conv_templates, SeparatorStyle
from llava.model.builder import load_pretrained_model
from llava.utils import disable_torch_init
from llava.mm_utils import get_model_name_from_path

print("Imports OK")

"""## 4. Image and latent utilities"""

def pad_image(image):
    width, height = image.size
    if width > height:
        new_width = new_height = width
    else:
        new_width = new_height = height

    new_im = Image.new("RGB", (new_width, new_height))
    new_im.paste(
        image,
        ((new_width - width) // 2, (new_height - height) // 2)
    )
    return new_im.resize((768, 768))


def load_image(path):
    return pad_image(Image.open(path).convert("RGB"))


@torch.no_grad()
def pil_to_latents(image, vae):
    x = tfms.ToTensor()(image).unsqueeze(0) * 2.0 - 1.0
    x = x.to("cuda", dtype=torch.float16)
    return vae.encode(x).latent_dist.sample() * 0.18215


@torch.no_grad()
def path_to_latents(paths, vae, mixup=False):
    images = [load_image(p) for p in paths]

    if mixup:
        lambdas = np.random.beta(0.2, 0.2, size=len(images))
        mixed_images = []
        for i in range(len(images)):
            i1 = random.randint(0, len(images) - 1)
            i2 = random.randint(0, len(images) - 1)
            mixed_images.append(
                Image.blend(images[i1], images[i2], lambdas[i])
            )
        images = mixed_images

    return torch.cat([pil_to_latents(img, vae) for img in images])


@torch.no_grad()
def latents_to_pil(latents, vae):
    latents = latents / 0.18215
    image = vae.decode(latents).sample
    image = (image / 2 + 0.5).clamp(0, 1)
    image = image.detach().cpu().permute(0, 2, 3, 1).numpy()
    image = (image * 255).round().astype("uint8")
    return [Image.fromarray(x) for x in image]


@torch.no_grad()
def text_enc(prompts, tokenizer, text_encoder, maxlen=None):
    if maxlen is None:
        maxlen = tokenizer.model_max_length

    inp = tokenizer(
        prompts,
        padding="max_length",
        max_length=maxlen,
        truncation=True,
        return_tensors="pt",
    )
    return text_encoder(inp.input_ids.to("cuda"))[0].half()

"""## 5. Load Stable Diffusion"""

def load_stable_diffusion(model_name):
    print("Loading Stable Diffusion...")

    model_id = (
        SD_MODEL_ID
        if model_name == "stable_diffusion"
        else "SG161222/Realistic_Vision_V2.0"
    )

    pipe = StableDiffusionPipeline.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
    )
    pipe = pipe.to("cuda")

    scheduler = DPMSolverMultistepScheduler.from_config(
        pipe.scheduler.config
    )
    scheduler.set_timesteps(20)
    pipe.scheduler = scheduler

    print("Stable Diffusion loaded.")
    return (
        pipe.vae,
        pipe.unet,
        pipe.scheduler,
        pipe.tokenizer,
        pipe.text_encoder,
    )

"""## 6. Load LLaVA"""

def load_llava(model_path):
    print("Loading LLaVA...")
    disable_torch_init()

    model_name = get_model_name_from_path(model_path)

    (
        llava_tokenizer,
        llava_model,
        llava_image_processor,
        context_len,
    ) = load_pretrained_model(
        model_path,
        None,
        model_name,
        False,
        False,
    )

    llava_processor = LlaVaProcessor(
        llava_tokenizer,
        llava_image_processor,
        llava_model.config.mm_use_im_start_end,
    )

    print("LLaVA loaded.")
    return (
        llava_tokenizer,
        llava_model,
        llava_image_processor,
        context_len,
        llava_processor,
    )


def caption_image(
    images_path,
    class_name,
    llava_tokenizer,
    llava_model,
    llava_processor,
):
    query = (
        f"Provide a detailed caption for the image focusing on the object, "
        f"knowing it's a {class_name}."
    )

    batch_images, batch_text = (
        llava_processor.get_processed_tokens_batch(
            [query] * len(images_path),
            images_path,
        )
    )

    conv = conv_templates[llava_processor.conv_mode].copy()
    stop_str = (
        conv.sep
        if conv.sep_style != SeparatorStyle.TWO
        else conv.sep2
    )

    input_ids = batch_text.cuda()

    with torch.inference_mode():
        output_ids = llava_model.generate(
            input_ids,
            images=batch_images.half().cuda(),
            do_sample=True,
            temperature=0.2,
            max_new_tokens=1024,
            use_cache=True,
        )

    outputs = llava_tokenizer.batch_decode(
        output_ids[:, input_ids.shape[1]:],
        skip_special_tokens=True,
    )

    outputs = [x.strip() for x in outputs]
    outputs = [
        x[:-len(stop_str)] if x.endswith(stop_str) else x
        for x in outputs
    ]

    return [x.strip() for x in outputs]

"""## 7. Load Qwen3-VL-Embedding-2B

This replaces CLIP. Qwen is used to create class text prototypes and to embed generated images.

"""

def load_qwen_model(model_path):
    print("Loading Qwen3-VL...")
    print("Model path:", model_path)

    qwen_model = Qwen3VLEmbedder(
        model_name_or_path=model_path
    )
    qwen_model.model.eval()

    print("Qwen3-VL loaded.")
    return qwen_model

QWEN_MODEL_PATH = '/content/SPC/models/Qwen3-VL-Embedding-2B'
qwen_model = load_qwen_model(QWEN_MODEL_PATH)

"""## 8. Build Qwen zero-shot class prototypes"""

@torch.no_grad()
def build_qwen_zeroshot_weights(
    dataset,
    class_names,
    qwen_model,
):
    dataset_name = get_dataset_name_for_template(dataset)
    prototypes = []

    qwen_model.model.to("cuda")
    qwen_model.model.eval()

    for class_name in class_names:
        class_texts = [
            {
                "text": template.format(
                    dataset_name,
                    class_name
                ) + "."
            }
            for template in TEMPLATES_SMALL
        ]

        class_embs = qwen_model.process(class_texts)
        class_embs = F.normalize(class_embs, dim=-1)

        prototype = class_embs.mean(dim=0)
        prototype = F.normalize(prototype, dim=-1)

        prototypes.append(prototype)

    weights = torch.stack(prototypes)

    qwen_model.model.to("cpu")
    torch.cuda.empty_cache()

    return weights

"""## 9. Find dataset classes"""

dataset = 'fgvc_aircraft'
class_names = SUBSET_NAMES[dataset]
class_names

"""## 10. Build Qwen prototypes"""



qwen_zeroshot_weights = build_qwen_zeroshot_weights(
    DATASET,
    class_names,
    qwen_model,
)

print("Prototype shape:", qwen_zeroshot_weights.shape)

"""## 11. Load Stable Diffusion and LLaVA"""

vae, unet, scheduler, tokenizer, text_encoder = (
    load_stable_diffusion(SD_MODEL_NAME)
)

if USE_LLAVA:
    (
        llava_tokenizer,
        llava_model,
        llava_image_processor,
        context_len,
        llava_processor,
    ) = load_llava(LLAVA_MODEL_PATH)
else:
    captions_path = f"{SPC_ROOT}/captions/{DATASET}.pkl"
    available_captions = pickle.load(
        open(captions_path, "rb")
    )

print("Generation models loaded.")

"""## 12. Qwen image filtering"""

@torch.no_grad()
def classify_images_with_qwen(
    images,
    zeroshot_weights,
    qwen_model,
):
    qwen_model.model.to("cuda")
    qwen_model.model.eval()

    image_features = get_image_embedding(
        qwen_model,
        images
    )
    image_features = F.normalize(
        image_features,
        dim=-1
    )

    qwen_model.model.to("cpu")
    torch.cuda.empty_cache()

    # Normalized image and text embeddings -> cosine similarity
    similarities = (
        image_features.to(zeroshot_weights.dtype)
        @ zeroshot_weights.T
    )

    predicted_classes = similarities.argmax(dim=-1)

    return predicted_classes, similarities

"""## 13. Generate and filter images

For each target class:

1. Randomly select few-shot real images.
2. Encode them to Stable Diffusion latents.
3. Add noise.
4. Use LLaVA to create captions.
5. Denoise with Stable Diffusion using CFG.
6. Decode generated images.
7. Embed generated images with Qwen.
8. Compare them with Qwen text prototypes.
9. Save only images classified as the target class.

"""

def get_filtered_paths(dataset_name, n_samples_per_class, real_data_dir):
    print(f"Lọc {n_samples_per_class}-shot dữ liệu gốc từ {real_data_dir}...")
    train_loader, _ = get_data_loader(
        real_train_data_dir=real_data_dir,
        real_test_data_dir=real_data_dir,
        dataset=dataset_name,
        bs=1, eval_bs=1,
        n_img_per_cls=n_samples_per_class,
        model_type="qwen"
    )

    train_dataset = train_loader.dataset
    class_names = SUBSET_NAMES[dataset_name]
    paths_dict = {cls: [] for cls in class_names}

    if dataset_name in ['dtd', 'flowers102', 'food101', 'sun397', 'fgvc_aircraft']:
        _images = train_dataset._image_files
        _labels = train_dataset._labels
    elif dataset_name == 'eurosat':
        _images = [sample[0] for sample in train_dataset.samples]
        _labels = [sample[1] for sample in train_dataset.samples]
    elif dataset_name == 'pets':
        _images = train_dataset._images
        _labels = train_dataset._labels
    elif dataset_name == 'cars':
        _images = [sample[0] for sample in train_dataset._samples]
        _labels = [sample[1] for sample in train_dataset._samples]
    elif dataset_name == 'caltech101':
        _images = [
            os.path.join(
                train_dataset.root,
                "caltech101",
                "101_ObjectCategories",
                train_dataset.categories[train_dataset.y[i]],
                f"image_{train_dataset.index[i]:04d}.jpg"
            ) for i in range(len(train_dataset.index))
        ]
        _labels = train_dataset.y
    else:
        raise ValueError(f"Dataset {dataset_name} not supported.")

    for img_path, label in zip(_images, _labels):
        class_name = class_names[label]
        paths_dict[class_name].append(img_path)

    return paths_dict, class_names

n_samples = 16
real_data_dir = "/content/SPC/data"
paths_dict, class_names = get_filtered_paths(dataset, n_samples, real_data_dir)

class_names[:10]

out_root = "/content/SPC/out_qwen"

DATA_ROOT = "/content/SPC/data/train/fgvc-aircraft-2013b/data/images"

paths_dict['707-320']

import os
import glob
import random

# Sửa đường dẫn này theo dataset của bạn
TEST_CLASS = '707-320'

TEST_DIR = os.path.join(
    DATA_ROOT,
    TEST_CLASS
)

image_extensions = (
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.JPG",
    "*.JPEG",
    "*.PNG",
)

test_paths = []

for ext in image_extensions:
    test_paths.extend(
        glob.glob(
            os.path.join(TEST_DIR, ext)
        )
    )

random.seed(42)
test_paths = paths_dict[TEST_CLASS]
random.shuffle(test_paths)

# Chỉ lấy 8 ảnh
test_paths = test_paths[:8]

print("Number of test images:", len(test_paths))

for i, path in enumerate(test_paths):
    print(f"[{i}] {path}")

captions = caption_image(
    test_paths,
    TEST_CLASS,
    llava_tokenizer,
    llava_model,
    llava_processor,
)

captions

# ============================================================
# QWEN ZERO-SHOT CLASSIFIER
# ============================================================

import gc
import math
import random
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt


NUM_DENOISING_STEPS = 20

# Keep approximately 25% noise
# according to the original 20-step schedule
STARTING_STEP = 15

# ============================================================
# GENERATION
# ============================================================

for idx, class_ in enumerate(
    class_names
):

    # --------------------------------------------------------
    # 0. Input / output directories
    # --------------------------------------------------------

    #class_dir = os.path.join(
    #    DATA_ROOT,
    #    class_
    #)

    class_dir = DATA_ROOT
    output_dir = os.path.join(
        out_root,
        class_
    )

    # Images before Qwen filtering
    before_qwen_dir = os.path.join(
        out_root,
        "_before_qwen",
        class_
    )

    os.makedirs(
        output_dir,
        exist_ok=True
    )

    os.makedirs(
        before_qwen_dir,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Check class directory
    # --------------------------------------------------------

    if not os.path.isdir(
        class_dir
    ):

        print(
            f"\nWARNING: class directory not found: "
            f"{class_dir}"
        )

        continue

    # --------------------------------------------------------
    # 1. Get available real images
    # --------------------------------------------------------

    available_files = [
        x
        for x in os.listdir(
            class_dir
        )
        if x.lower().endswith(
            (
                ".jpg",
                ".jpeg",
                ".png",
                ".webp"
            )
        )
    ]
    # airc
    available_files = paths_dict[class_]

    if not available_files:

        print(
            f"Skipping empty class: {class_}"
        )

        continue

    # --------------------------------------------------------
    # 2. Count existing Qwen-filtered images
    # --------------------------------------------------------

    generated_this_class = len(
        [
            x
            for x in os.listdir(
                output_dir
            )
            if x.lower().endswith(
                (
                    ".jpg",
                    ".jpeg",
                    ".png",
                    ".webp"
                )
            )
        ]
    )

    # --------------------------------------------------------
    # Cycle counter
    # --------------------------------------------------------

    cycles_spent_this_class = 0

    # Cache LLaVA captions
    prompt_cache = {}

    print(
        f"\n[{idx + 1}/{len(class_names)}] "
        f"{class_}: "
        f"{generated_this_class}/"
        f"{IMAGES_PER_CLASS}"
    )

    print(
        f"  Input: {class_dir}"
    )

    print(
        f"  Output: {output_dir}"
    )

    print(
        f"  Before-Qwen: {before_qwen_dir}"
    )

    # ========================================================
    # Generation loop
    # ========================================================

    while (
        generated_this_class
        < IMAGES_PER_CLASS
    ):

        cycles_spent_this_class += 1

        print(
            "\n"
            + "=" * 70
        )

        print(
            f"Class: {class_} | "
            f"Cycle: {cycles_spent_this_class} | "
            f"Accepted: "
            f"{generated_this_class}/"
            f"{IMAGES_PER_CLASS}"
        )

        print(
            "=" * 70
        )

        # ====================================================
        # 1. ORIGINAL 20-STEP SCHEDULE
        #
        # Used ONLY to determine starting noise level.
        # ====================================================

        scheduler.set_timesteps(
            NUM_DENOISING_STEPS
        )

        original_timesteps = (
            scheduler.timesteps.clone()
        )

        # ----------------------------------------------------
        # STARTING_STEP = 15
        # approximately 25% noise
        # ----------------------------------------------------

        start_timestep = (
            original_timesteps[
                STARTING_STEP
            ].item()
        )

        print(
            "\nOriginal scheduler timesteps:"
        )

        print(
            original_timesteps.tolist()
        )

        print(
            f"STARTING_STEP = "
            f"{STARTING_STEP}"
        )

        print(
            f"Starting timestep = "
            f"{start_timestep}"
        )

        # ====================================================
        # 2. Sample real few-shot images
        # ====================================================

        file_names = random.choices(
            available_files,
            k=BATCH_SIZE
        )

        file_paths = [
            os.path.join(
                class_dir,
                x
            )
            for x in file_names
        ]

        # ====================================================
        # 3. Real image -> latent
        # ====================================================

        latents = path_to_latents(
            file_paths,
            vae,
            MIXUP
        )

        # ====================================================
        # 4. Add noise
        # ====================================================

        noise = torch.randn_like(
            latents
        )

        noised_latents = scheduler.add_noise(
            latents,
            noise,
            timesteps=torch.tensor(
                [start_timestep],
                device=latents.device,
                dtype=torch.long
            )
        )

        print(
            f"Added noise at timestep "
            f"{start_timestep}"
        )

        # ====================================================
        # 5. LLaVA caption
        # ====================================================

        if USE_LLAVA:

            missing_indices = [
                i
                for i, f in enumerate(file_names)
                if f not in prompt_cache
            ]

            if missing_indices:

                missing_paths = [
                    file_paths[i]
                    for i in missing_indices
                ]

                missing_prompts = caption_image(
                    missing_paths,
                    class_,
                    llava_tokenizer,
                    llava_model,
                    llava_processor
                )

                if len(
                    missing_prompts
                ) != len(
                    missing_indices
                ):

                    raise RuntimeError(
                        "Number of LLaVA captions "
                        "does not match number of images."
                    )

                for j, original_idx in enumerate(
                    missing_indices
                ):

                    caption = (
                        missing_prompts[j]
                    )

                    if caption is None:
                        caption = ""

                    caption = str(
                        caption
                    ).strip()

                    prompt_cache[
                        file_names[
                            original_idx
                        ]
                    ] = caption

            # ------------------------------------------------
            # Get captions corresponding to images
            # ------------------------------------------------

            prompts = []

            for f in file_names:

                prompt = prompt_cache.get(
                    f,
                    ""
                )

                if prompt is None:
                    prompt = ""

                prompt = str(
                    prompt
                ).strip()

                # ------------------------------------------------
                # Fallback if LLaVA caption is empty
                # ------------------------------------------------

                if len(prompt) < 10:

                    prompt = (
                        f"a centered satellite photo "
                        f"of a {class_}."
                    )

                prompts.append(
                    prompt
                )

            # IMPORTANT:
            # Do NOT shuffle prompts.
            #
            # image_i <-> caption_i

        else:

            prompts_this_class = (
                available_captions[
                    class_
                ]
            )

            try:

                prompts = random.choices(
                    prompts_this_class,
                    k=BATCH_SIZE
                )

            except Exception:

                prompts = [
                    f"a centered satellite photo "
                    f"of a {class_}."
                    for _ in range(BATCH_SIZE)
                ]

        # ====================================================
        # 6. Print prompts
        # ====================================================

        print(
            "\nPrompts used for generation:"
        )

        for i, prompt in enumerate(
            prompts
        ):

            print(
                f"  [{i}] "
                f"{repr(prompt)}"
            )
            break
        # ====================================================
        # 7. Text embedding
        # ====================================================

        text_embed = text_enc(
            prompts,
            tokenizer,
            text_encoder
        )

        # ====================================================
        # 8. Unconditional embedding
        # ====================================================

        uncond = text_enc(
            [""] * 1,
            tokenizer,
            text_encoder,
            text_embed.shape[1]
        ).repeat(
            BATCH_SIZE,
            1,
            1
        )

        # ====================================================
        # 9. CFG embedding
        # ====================================================

        emb = torch.cat(
            [
                uncond,
                text_embed
            ]
        )

        # ====================================================
        # 10. CREATE 20 DENOISING TIMESTEPS
        #
        # 25% noise -> 20 denoising steps -> 0
        # ====================================================

        denoising_timesteps = (
            torch.linspace(
                start_timestep,
                0,
                NUM_DENOISING_STEPS,
                device="cpu"
            )
            .round()
            .long()
        )

        # Remove duplicates
        denoising_timesteps = (
            torch.unique(
                denoising_timesteps,
                sorted=True
            )
            .flip(0)
        )

        print(
            "\nCustom denoising timesteps:"
        )

        print(
            denoising_timesteps.tolist()
        )

        print(
            "Number of denoising steps:",
            len(denoising_timesteps)
        )

        # ====================================================
        # 11. Set scheduler
        # ====================================================

        scheduler.set_timesteps(
            timesteps=denoising_timesteps,
            device=latents.device
        )

        # ====================================================
        # 12. DENOISING
        # ====================================================

        latents = noised_latents

        unet.to("cuda")

        for step_idx, ts in enumerate(
            scheduler.timesteps
        ):

            print(
                f"\rDenoising: "
                f"{step_idx + 1}/"
                f"{len(scheduler.timesteps)}",
                end=""
            )

            # ------------------------------------------------
            # CFG input
            # ------------------------------------------------

            inp = (
                scheduler.scale_model_input(
                    torch.cat(
                        [latents] * 2
                    ),
                    ts
                )
            )

            # ------------------------------------------------
            # UNet
            # ------------------------------------------------

            with torch.no_grad(), torch.autocast(
                "cuda"
            ):

                unconditional, conditional = (
                    unet(
                        inp,
                        ts,
                        encoder_hidden_states=emb
                    )
                    .sample
                    .chunk(2)
                )

            # ------------------------------------------------
            # Classifier-Free Guidance
            # ------------------------------------------------

            predicted_sample = (
                unconditional
                + CFG_STRENGTH
                * (
                    conditional
                    - unconditional
                )
            )

            # ------------------------------------------------
            # DPMSolver++
            # ------------------------------------------------

            latents = scheduler.step(
                predicted_sample,
                ts,
                latents
            ).prev_sample

        print()

        unet.to("cpu")

        torch.cuda.empty_cache()

        # ====================================================
        # 13. Latent -> PIL
        # ====================================================

        final_imgs = latents_to_pil(
            latents,
            vae
        )

        # ====================================================
        # 14. Resize for display / saving
        # ====================================================

        final_imgs_highres = [
            img.resize(
                (512, 512)
            )
            for img in final_imgs
        ]

        # ====================================================
        # 15. DISPLAY BEFORE QWEN
        # ====================================================

        print(
            f"\nGenerated "
            f"{len(final_imgs_highres)} "
            f"images BEFORE Qwen filtering."
        )

        print(
            f"Target class: {class_}"
        )

        cols = min(
            4,
            len(final_imgs_highres)
        )

        rows = math.ceil(
            len(final_imgs_highres)
            / cols
        )

        #plt.figure(
           # figsize=(
            #    4 * cols,
            #    4 * rows
         #   )
        #)

        #for i, img in enumerate(
        #    final_imgs_highres
        #):

          #  ax = plt.subplot(
           #     rows,
            #    cols,
            #    i + 1
            #)

            #ax.imshow(img)

            #ax.set_title(
             #   f"Target: {class_}\n"
             #   f"Sample {i + 1}"
            #)

            #ax.axis("off")

        #plt.tight_layout()

        plt.show()

        # ====================================================
        # 16. SAVE ALL IMAGES BEFORE QWEN
        # ====================================================

        #for i, img in enumerate(
        #    final_imgs_highres
        #):

           # before_qwen_path = os.path.join(
            #    before_qwen_dir,
             #   f"{class_}_"
              #  f"cycle_{cycles_spent_this_class}_"
               # f"sample_{i}.jpg"
           # )

            #img.save(
             #   before_qwen_path
            #)

        #print(
         #   "\nSaved BEFORE-QWEN images to:"
        #)

        #print(
         #   before_qwen_dir
        #)

        # ====================================================
        # 17. QWEN FILTER
        # ====================================================

        print(
            "\nQwen filtering:"
        )

        predicted_classes, similarities = (
            classify_images_with_qwen(
                final_imgs,
                qwen_zeroshot_weights,
                qwen_model,
            )
        )

        # ====================================================
        # 18. ACCEPT / DROP
        # ====================================================

        for i, img in enumerate(
            final_imgs_highres
        ):

            # ------------------------------------------------
            # Stop once target number is reached
            # ------------------------------------------------

            if (
                generated_this_class
                >= IMAGES_PER_CLASS
            ):
                break

            # ------------------------------------------------
            # Qwen prediction
            # ------------------------------------------------

            predicted_class = int(
                predicted_classes[i].item()
            )

            predicted_name = (
                class_names[
                    predicted_class
                ]
            )

            # ------------------------------------------------
            # Similarity
            # ------------------------------------------------

            similarity_score = float(
                similarities[
                    i,
                    predicted_class
                ].item()
            )

            # ------------------------------------------------
            # Correct?
            # ------------------------------------------------

            is_correct = (
                predicted_class == idx
            )

            # ------------------------------------------------
            # Accept / reject
            # ------------------------------------------------

            accept = (
                is_correct
                or
                cycles_spent_this_class > 100
            )

            # =================================================
            # SAVE
            # =================================================

            if accept:

                random_name = random.randint(
                    0,
                    1_000_000_000
                )

                out_path = os.path.join(
                    output_dir,
                    f"{class_}_"
                    f"{generated_this_class}_"
                    f"{random_name}.jpg"
                )

                img.save(
                    out_path
                )

                generated_this_class += 1

                if is_correct:

                    print(
                        f"  SAVE | "
                        f"target={class_} | "
                        f"Qwen={predicted_name} | "
                        f"similarity="
                        f"{similarity_score:.4f} | "
                        f"{generated_this_class}/"
                        f"{IMAGES_PER_CLASS}"
                    )

                else:

                    print(
                        f"  SAVE-FALLBACK | "
                        f"target={class_} | "
                        f"Qwen={predicted_name} | "
                        f"similarity="
                        f"{similarity_score:.4f} | "
                        f"{generated_this_class}/"
                        f"{IMAGES_PER_CLASS}"
                    )

            # =================================================
            # DROP
            # =================================================

            else:

                print(
                    f"  DROP | "
                    f"target={class_} | "
                    f"Qwen={predicted_name} | "
                    f"similarity="
                    f"{similarity_score:.4f}"
                )

        # ====================================================
        # 19. Recount accepted images
        # ====================================================

        generated_files = [
            x
            for x in os.listdir(
                output_dir
            )
            if x.lower().endswith(
                (
                    ".jpg",
                    ".jpeg",
                    ".png",
                    ".webp"
                )
            )
        ]

        generated_this_class = len(
            generated_files
        )

        print(
            f"\nAfter Qwen: "
            f"{generated_this_class}/"
            f"{IMAGES_PER_CLASS}"
        )

        # ====================================================
        # 20. Memory cleanup
        # ====================================================

        del latents
        del noised_latents
        del noise
        del text_embed
        del uncond
        del emb

        torch.cuda.empty_cache()

        gc.collect()

        # ====================================================
        # 21. Prevent infinite loop
        # ====================================================

        if cycles_spent_this_class > 100:

            print(
                f"\nReached 100 cycles for "
                f"{class_}."
            )

            print(
                f"Current accepted count: "
                f"{generated_this_class}/"
                f"{IMAGES_PER_CLASS}"
            )

            break


# ============================================================
# Generation finished
# ============================================================

print(
    "\n"
    + "=" * 70
)

print(
    "GENERATION FINISHED"
)

print(
    "=" * 70
)

print(
    "Output:",
    out_root
)

print(
    "\nPipeline:"
)

print(
    "25% noise"
)

print(
    "    ↓"
)

print(
    "20-step DPMSolver++ denoising"
)

print(
    "    ↓"
)

print(
    "Generated image"
)

print(
    "    ↓"
)

print(
    "Qwen filtering"
)

print(
    "    ↓"
)

print(
    "Correct class → SAVE"
)

print(
    "Wrong class → DROP"
)

# ============================================================
# QWEN ZERO-SHOT CLASSIFIER
# ============================================================

import gc
import math
import random
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt


NUM_DENOISING_STEPS = 20

# Keep approximately 25% noise
# according to the original 20-step schedule
STARTING_STEP = 15

# ============================================================
# GENERATION
# ============================================================

for idx, class_ in enumerate(
    class_names
):

    # --------------------------------------------------------
    # 0. Input / output directories
    # --------------------------------------------------------

    class_dir = os.path.join(
        DATA_ROOT,
        class_
    )

    output_dir = os.path.join(
        out_root,
        class_
    )

    # Images before Qwen filtering
    before_qwen_dir = os.path.join(
        out_root,
        "_before_qwen",
        class_
    )

    os.makedirs(
        output_dir,
        exist_ok=True
    )

    os.makedirs(
        before_qwen_dir,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Check class directory
    # --------------------------------------------------------

    if not os.path.isdir(
        class_dir
    ):

        print(
            f"\nWARNING: class directory not found: "
            f"{class_dir}"
        )

        continue

    # --------------------------------------------------------
    # 1. Get available real images
    # --------------------------------------------------------

    available_files = [
        x
        for x in os.listdir(
            class_dir
        )
        if x.lower().endswith(
            (
                ".jpg",
                ".jpeg",
                ".png",
                ".webp"
            )
        )
    ]

    if not available_files:

        print(
            f"Skipping empty class: {class_}"
        )

        continue

    # --------------------------------------------------------
    # 2. Count existing Qwen-filtered images
    # --------------------------------------------------------

    generated_this_class = len(
        [
            x
            for x in os.listdir(
                output_dir
            )
            if x.lower().endswith(
                (
                    ".jpg",
                    ".jpeg",
                    ".png",
                    ".webp"
                )
            )
        ]
    )

    # --------------------------------------------------------
    # Cycle counter
    # --------------------------------------------------------

    cycles_spent_this_class = 0

    # Cache LLaVA captions
    prompt_cache = {}

    print(
        f"\n[{idx + 1}/{len(class_names)}] "
        f"{class_}: "
        f"{generated_this_class}/"
        f"{IMAGES_PER_CLASS}"
    )

    print(
        f"  Input: {class_dir}"
    )

    print(
        f"  Output: {output_dir}"
    )

    print(
        f"  Before-Qwen: {before_qwen_dir}"
    )

    # ========================================================
    # Generation loop
    # ========================================================

    while (
        generated_this_class
        < IMAGES_PER_CLASS
    ):

        cycles_spent_this_class += 1

        print(
            "\n"
            + "=" * 70
        )

        print(
            f"Class: {class_} | "
            f"Cycle: {cycles_spent_this_class} | "
            f"Accepted: "
            f"{generated_this_class}/"
            f"{IMAGES_PER_CLASS}"
        )

        print(
            "=" * 70
        )

        # ====================================================
        # 1. ORIGINAL 20-STEP SCHEDULE
        #
        # Used ONLY to determine starting noise level.
        # ====================================================

        scheduler.set_timesteps(
            NUM_DENOISING_STEPS
        )

        original_timesteps = (
            scheduler.timesteps.clone()
        )

        # ----------------------------------------------------
        # STARTING_STEP = 15
        # approximately 25% noise
        # ----------------------------------------------------

        start_timestep = (
            original_timesteps[
                STARTING_STEP
            ].item()
        )

        print(
            "\nOriginal scheduler timesteps:"
        )

        print(
            original_timesteps.tolist()
        )

        print(
            f"STARTING_STEP = "
            f"{STARTING_STEP}"
        )

        print(
            f"Starting timestep = "
            f"{start_timestep}"
        )

        # ====================================================
        # 2. Sample real few-shot images
        # ====================================================

        file_names = random.choices(
            available_files,
            k=BATCH_SIZE
        )

        file_paths = [
            os.path.join(
                class_dir,
                x
            )
            for x in file_names
        ]

        # ====================================================
        # 3. Real image -> latent
        # ====================================================

        latents = path_to_latents(
            file_paths,
            vae,
            MIXUP
        )

        # ====================================================
        # 4. Add noise
        # ====================================================

        noise = torch.randn_like(
            latents
        )

        noised_latents = scheduler.add_noise(
            latents,
            noise,
            timesteps=torch.tensor(
                [start_timestep],
                device=latents.device,
                dtype=torch.long
            )
        )

        print(
            f"Added noise at timestep "
            f"{start_timestep}"
        )

        # ====================================================
        # 5. LLaVA caption
        # ====================================================

        if USE_LLAVA:

            missing_indices = [
                i
                for i, f in enumerate(file_names)
                if f not in prompt_cache
            ]

            if missing_indices:

                missing_paths = [
                    file_paths[i]
                    for i in missing_indices
                ]

                missing_prompts = caption_image(
                    missing_paths,
                    class_,
                    llava_tokenizer,
                    llava_model,
                    llava_processor
                )

                if len(
                    missing_prompts
                ) != len(
                    missing_indices
                ):

                    raise RuntimeError(
                        "Number of LLaVA captions "
                        "does not match number of images."
                    )

                for j, original_idx in enumerate(
                    missing_indices
                ):

                    caption = (
                        missing_prompts[j]
                    )

                    if caption is None:
                        caption = ""

                    caption = str(
                        caption
                    ).strip()

                    prompt_cache[
                        file_names[
                            original_idx
                        ]
                    ] = caption

            # ------------------------------------------------
            # Get captions corresponding to images
            # ------------------------------------------------

            prompts = []

            for f in file_names:

                prompt = prompt_cache.get(
                    f,
                    ""
                )

                if prompt is None:
                    prompt = ""

                prompt = str(
                    prompt
                ).strip()

                # ------------------------------------------------
                # Fallback if LLaVA caption is empty
                # ------------------------------------------------

                if len(prompt) < 10:

                    prompt = (
                        f"a centered satellite photo "
                        f"of a {class_}."
                    )

                prompts.append(
                    prompt
                )

            # IMPORTANT:
            # Do NOT shuffle prompts.
            #
            # image_i <-> caption_i

        else:

            prompts_this_class = (
                available_captions[
                    class_
                ]
            )

            try:

                prompts = random.choices(
                    prompts_this_class,
                    k=BATCH_SIZE
                )

            except Exception:

                prompts = [
                    f"a centered satellite photo "
                    f"of a {class_}."
                    for _ in range(BATCH_SIZE)
                ]

        # ====================================================
        # 6. Print prompts
        # ====================================================

        print(
            "\nPrompts used for generation:"
        )

        for i, prompt in enumerate(
            prompts
        ):

            print(
                f"  [{i}] "
                f"{repr(prompt)}"
            )

        # ====================================================
        # 7. Text embedding
        # ====================================================

        text_embed = text_enc(
            prompts,
            tokenizer,
            text_encoder
        )

        # ====================================================
        # 8. Unconditional embedding
        # ====================================================

        uncond = text_enc(
            [""] * 1,
            tokenizer,
            text_encoder,
            text_embed.shape[1]
        ).repeat(
            BATCH_SIZE,
            1,
            1
        )

        # ====================================================
        # 9. CFG embedding
        # ====================================================

        emb = torch.cat(
            [
                uncond,
                text_embed
            ]
        )

        # ====================================================
        # 10. CREATE 20 DENOISING TIMESTEPS
        #
        # 25% noise -> 20 denoising steps -> 0
        # ====================================================

        denoising_timesteps = (
            torch.linspace(
                start_timestep,
                0,
                NUM_DENOISING_STEPS,
                device="cpu"
            )
            .round()
            .long()
        )

        # Remove duplicates
        denoising_timesteps = (
            torch.unique(
                denoising_timesteps,
                sorted=True
            )
            .flip(0)
        )

        print(
            "\nCustom denoising timesteps:"
        )

        print(
            denoising_timesteps.tolist()
        )

        print(
            "Number of denoising steps:",
            len(denoising_timesteps)
        )

        # ====================================================
        # 11. Set scheduler
        # ====================================================

        scheduler.set_timesteps(
            timesteps=denoising_timesteps,
            device=latents.device
        )

        # ====================================================
        # 12. DENOISING
        # ====================================================

        latents = noised_latents

        unet.to("cuda")

        for step_idx, ts in enumerate(
            scheduler.timesteps
        ):

            print(
                f"\rDenoising: "
                f"{step_idx + 1}/"
                f"{len(scheduler.timesteps)}",
                end=""
            )

            # ------------------------------------------------
            # CFG input
            # ------------------------------------------------

            inp = (
                scheduler.scale_model_input(
                    torch.cat(
                        [latents] * 2
                    ),
                    ts
                )
            )

            # ------------------------------------------------
            # UNet
            # ------------------------------------------------

            with torch.no_grad(), torch.autocast(
                "cuda"
            ):

                unconditional, conditional = (
                    unet(
                        inp,
                        ts,
                        encoder_hidden_states=emb
                    )
                    .sample
                    .chunk(2)
                )

            # ------------------------------------------------
            # Classifier-Free Guidance
            # ------------------------------------------------

            predicted_sample = (
                unconditional
                + CFG_STRENGTH
                * (
                    conditional
                    - unconditional
                )
            )

            # ------------------------------------------------
            # DPMSolver++
            # ------------------------------------------------

            latents = scheduler.step(
                predicted_sample,
                ts,
                latents
            ).prev_sample

        print()

        unet.to("cpu")

        torch.cuda.empty_cache()

        # ====================================================
        # 13. Latent -> PIL
        # ====================================================

        final_imgs = latents_to_pil(
            latents,
            vae
        )

        # ====================================================
        # 14. Resize for display / saving
        # ====================================================

        final_imgs_highres = [
            img.resize(
                (512, 512)
            )
            for img in final_imgs
        ]

        # ====================================================
        # 15. DISPLAY BEFORE QWEN
        # ====================================================

        print(
            f"\nGenerated "
            f"{len(final_imgs_highres)} "
            f"images BEFORE Qwen filtering."
        )

        print(
            f"Target class: {class_}"
        )

        cols = min(
            4,
            len(final_imgs_highres)
        )

        rows = math.ceil(
            len(final_imgs_highres)
            / cols
        )

        plt.figure(
            figsize=(
                4 * cols,
                4 * rows
            )
        )

        for i, img in enumerate(
            final_imgs_highres
        ):

            ax = plt.subplot(
                rows,
                cols,
                i + 1
            )

            ax.imshow(img)

            ax.set_title(
                f"Target: {class_}\n"
                f"Sample {i + 1}"
            )

            ax.axis("off")

        plt.tight_layout()

        plt.show()

        # ====================================================
        # 16. SAVE ALL IMAGES BEFORE QWEN
        # ====================================================

        for i, img in enumerate(
            final_imgs_highres
        ):

            before_qwen_path = os.path.join(
                before_qwen_dir,
                f"{class_}_"
                f"cycle_{cycles_spent_this_class}_"
                f"sample_{i}.jpg"
            )

            img.save(
                before_qwen_path
            )

        print(
            "\nSaved BEFORE-QWEN images to:"
        )

        print(
            before_qwen_dir
        )

        # ====================================================
        # 17. QWEN FILTER
        # ====================================================

        print(
            "\nQwen filtering:"
        )

        predicted_classes, similarities = (
            classify_images_with_qwen(
                final_imgs,
                qwen_zeroshot_weights,
                qwen_model,
            )
        )

        # ====================================================
        # 18. ACCEPT / DROP
        # ====================================================

        for i, img in enumerate(
            final_imgs_highres
        ):

            # ------------------------------------------------
            # Stop once target number is reached
            # ------------------------------------------------

            if (
                generated_this_class
                >= IMAGES_PER_CLASS
            ):
                break

            # ------------------------------------------------
            # Qwen prediction
            # ------------------------------------------------

            predicted_class = int(
                predicted_classes[i].item()
            )

            predicted_name = (
                class_names[
                    predicted_class
                ]
            )

            # ------------------------------------------------
            # Similarity
            # ------------------------------------------------

            similarity_score = float(
                similarities[
                    i,
                    predicted_class
                ].item()
            )

            # ------------------------------------------------
            # Correct?
            # ------------------------------------------------

            is_correct = (
                predicted_class == idx
            )

            # ------------------------------------------------
            # Accept / reject
            # ------------------------------------------------

            accept = (
                is_correct
                or
                cycles_spent_this_class > 100
            )

            # =================================================
            # SAVE
            # =================================================

            if accept:

                random_name = random.randint(
                    0,
                    1_000_000_000
                )

                out_path = os.path.join(
                    output_dir,
                    f"{class_}_"
                    f"{generated_this_class}_"
                    f"{random_name}.jpg"
                )

                img.save(
                    out_path
                )

                generated_this_class += 1

                if is_correct:

                    print(
                        f"  SAVE | "
                        f"target={class_} | "
                        f"Qwen={predicted_name} | "
                        f"similarity="
                        f"{similarity_score:.4f} | "
                        f"{generated_this_class}/"
                        f"{IMAGES_PER_CLASS}"
                    )

                else:

                    print(
                        f"  SAVE-FALLBACK | "
                        f"target={class_} | "
                        f"Qwen={predicted_name} | "
                        f"similarity="
                        f"{similarity_score:.4f} | "
                        f"{generated_this_class}/"
                        f"{IMAGES_PER_CLASS}"
                    )

            # =================================================
            # DROP
            # =================================================

            else:

                print(
                    f"  DROP | "
                    f"target={class_} | "
                    f"Qwen={predicted_name} | "
                    f"similarity="
                    f"{similarity_score:.4f}"
                )

        # ====================================================
        # 19. Recount accepted images
        # ====================================================

        generated_files = [
            x
            for x in os.listdir(
                output_dir
            )
            if x.lower().endswith(
                (
                    ".jpg",
                    ".jpeg",
                    ".png",
                    ".webp"
                )
            )
        ]

        generated_this_class = len(
            generated_files
        )

        print(
            f"\nAfter Qwen: "
            f"{generated_this_class}/"
            f"{IMAGES_PER_CLASS}"
        )

        # ====================================================
        # 20. Memory cleanup
        # ====================================================

        del latents
        del noised_latents
        del noise
        del text_embed
        del uncond
        del emb

        torch.cuda.empty_cache()

        gc.collect()

        # ====================================================
        # 21. Prevent infinite loop
        # ====================================================

        if cycles_spent_this_class > 100:

            print(
                f"\nReached 100 cycles for "
                f"{class_}."
            )

            print(
                f"Current accepted count: "
                f"{generated_this_class}/"
                f"{IMAGES_PER_CLASS}"
            )

            break


# ============================================================
# Generation finished
# ============================================================

print(
    "\n"
    + "=" * 70
)

print(
    "GENERATION FINISHED"
)

print(
    "=" * 70
)

print(
    "Output:",
    out_root
)

print(
    "\nPipeline:"
)

print(
    "25% noise"
)

print(
    "    ↓"
)

print(
    "20-step DPMSolver++ denoising"
)

print(
    "    ↓"
)

print(
    "Generated image"
)

print(
    "    ↓"
)

print(
    "Qwen filtering"
)

print(
    "    ↓"
)

print(
    "Correct class → SAVE"
)

print(
    "Wrong class → DROP"
)

"""## 14. Check generated image counts"""

!zip -r /content/disef_synth_64.zip /content/SPC/out_qwen

counts = {}

for class_name in sorted(os.listdir(out_root)):
    class_path = os.path.join(
        out_root,
        class_name
    )

    if not os.path.isdir(class_path):
        continue

    counts[class_name] = len([
        x for x in os.listdir(class_path)
        if x.lower().endswith(
            (".jpg", ".jpeg", ".png")
        )
    ])

for class_name, count in counts.items():
    print(f"{class_name}: {count}")

print("Total generated:", sum(counts.values()))